version: '3'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
