services:
  app:
    build: .
    ports:
      - "60000:60000"  # FastAPI
    depends_on:
      - sonarqube
    networks:
      - sonarnet

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge
